version: "3"

services:
  svcuser:
    image: registry.cn-beijing.aliyuncs.com/tianyl/svcuser:v1
    networks:
      - user_net2
    deploy:
      mode: replicated
      replicas: 3
  webuser:
    image: registry.cn-beijing.aliyuncs.com/tianyl/webuser:v1
    ports:
      - 3000:3000
    environment:
      - USER_HOST=svcuser
    networks:
      - user_net2
    deploy:
      mode: replicated
      replicas: 2
networks:
  user_net2:
